import { randomUUID } from 'crypto';

// Storage paths are generated by the server and namespaced by their owner:
//   public/users/<userId>/<uuid>-<name>   public objects (avatars, logos, catalogue bottles)
//   private/users/<userId>/<uuid>-<name>  private objects in the main bucket
//   secure/<userId>/<uuid>-<name>         private objects in SUPABASE_PRIVATE_BUCKET
// Older uploads used public/uploads/<name> and private/uploads/<name>, which
// carry no owner, so their ownership can only be judged from the file records.

export type StorageVisibility = 'public' | 'private' | 'secure';

const USER_ID = /^[A-Za-z0-9-]{1,64}$/;
const NAMESPACED = /^(?:(?:public|private)\/users|secure)\/([^/]+)\/([^/]+)$/;
const NAMESPACE_PREFIXES = ['public/users/', 'private/users/', 'secure/'];
const SAFE_SEGMENT = /^[A-Za-z0-9][A-Za-z0-9._-]{0,254}$/;

export function sanitizeFileName(name: string | undefined): string {
  return (name || 'file').replace(/[^a-zA-Z0-9._-]/g, '_').slice(-120);
}

export function buildUserStoragePath(
  userId: string,
  fileName: string | undefined,
  visibility: StorageVisibility,
): string {
  if (!USER_ID.test(userId ?? '')) {
    throw new Error('Invalid user id for storage path');
  }
  const prefix = visibility === 'secure' ? `secure/${userId}/` : `${visibility}/users/${userId}/`;
  return `${prefix}${randomUUID()}-${sanitizeFileName(fileName)}`;
}

// Owner embedded in a namespaced path; '' for a malformed namespaced path;
// null for legacy or unknown formats that carry no owner.
export function namespacedOwner(path: string): string | null {
  if (typeof path !== 'string') return '';
  if (!NAMESPACE_PREFIXES.some((prefix) => path.startsWith(prefix))) return null;
  const match = NAMESPACED.exec(path);
  if (!match || !USER_ID.test(match[1]) || !SAFE_SEGMENT.test(match[2])) return '';
  return match[1];
}

export function isOwnedStoragePath(userId: string, path: string): boolean {
  return !!userId && namespacedOwner(path) === userId;
}

export function isPublicStoragePath(path: string): boolean {
  return path.startsWith('public/');
}

type StoredFile = { id: string; userid: string; cloudstoragepath: string; createdat?: Date };

// A record can be trusted when its path is in the owner's namespace, or, for
// legacy paths, when no other user registered the same path before it (a
// forged record always comes after the real owner's record).
export async function isTrustedFileRecord(prisma: any, file: StoredFile): Promise<boolean> {
  const owner = namespacedOwner(file.cloudstoragepath);
  if (owner !== null) return owner === file.userid;
  const earlier = await prisma.file.findFirst({
    where: {
      cloudstoragepath: file.cloudstoragepath,
      userid: { not: file.userid },
      ...(file.createdat && { createdat: { lt: file.createdat } }),
    },
    select: { id: true },
  });
  return !earlier;
}

// Deleting a record may only remove the storage object when the object is
// provably the record owner's. Legacy paths are deleted only when no other
// user's record references the same object.
export async function canDeleteStorageObject(prisma: any, file: StoredFile): Promise<boolean> {
  const owner = namespacedOwner(file.cloudstoragepath);
  if (owner !== null) return owner === file.userid;
  const other = await prisma.file.findFirst({
    where: {
      cloudstoragepath: file.cloudstoragepath,
      id: { not: file.id },
      userid: { not: file.userid },
    },
    select: { id: true },
  });
  return !other;
}
